[book]
authors = ["Oliver Wangler <oliver@wngr.de>"]
language = "en"
multilingual = false
src = "src"
description = "Persistent dumps of some of the thoughts that crossed my mind"
title = "wngr"

[rust]
edition = "2018"

[build]
build-dir = "public"

[output.html]
default-theme = "coal"
git-repository-url = "https://github.com/wngr/wngr.github.io/tree/main/src"

[output.html.print]
enable = false

[output.html.playground]
line-numbers = true
