name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: true
      - name: Install mdbook
        run: cargo install mdbook
      - name: mdbook test
        run: mdbook test
      - name: mdbook build
        run: mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

